# Generated by Django 6.0.5 on 2026-06-20 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('schedule', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Upcoming', max_length=20)),
                ('syllabus_progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assistant_manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'Assistant Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_batches', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(blank=True, limit_choices_to={'role': 'Trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
